version: '3'
services:

  postgres:
    # For more details on configuring the Postgres Docker image, see:
    #   https://hub.docker.com/_/postgres/
    image: postgres:latest

    # Expose the default Postgres port on localhost
    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: nestjs

    environment:
      POSTGRES_USER: 'tungjj'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'mydb'

    # Copy files from dbinit into the image so that they will be run on boot
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
